### PR TITLE
fix(docker): npm target with run

### PR DESCRIPTION
**Pull request by linuxbandit**

### CODE REVIEW

**Comment by linuxbandit** [comment]
> Can you also check why docker build and push fails before merging? Should be something with permissions as I can docker login but can't docker push (so the credentials should be right)

They look green here?

**Comment by serge1peshcoff** [comment]
The docker build and push is master only, and it still fails, check out https://github.com/AEGEE/oms-discounts/runs/253128026

**Comment by linuxbandit** [comment]
done, it was a thing on dockerhub (the group needed to be assigned the permissions over oms-discounts)

now i test your hotfix addition, but i presume you also tested it working?

**Comment by linuxbandit** [comment]
unfortunately it does not, and indeed the original dockerfile line is `CMD sh /usr/app/scripts/bootstrap.sh && npm start` (so, not too different than what i have done)

trying another thing now, let's see

**Comment by linuxbandit** [comment]
solved

**Comment by serge1peshcoff** [comment]
I wonder why did it work for me from the box

**Comment by linuxbandit** [comment]
i know right, if the boottrap script missed a +x permission then it makes no sense that it was working only for you..!

anyway i'll merge now

**Pull request merged**
